--
--  Copyright (C) 2019, AdaCore
--

--  Copyright (c) 2010 - 2017, Nordic Semiconductor ASA
--
--  All rights reserved.
--
--

--  This spec has been automatically generated from nrf52840.svd

pragma Ada_2012;
pragma Style_Checks (Off);

with System;

package Interfaces.NRF52.EGU is
   pragma Preelaborate;
   pragma No_Elaboration_Code_All;

   ---------------
   -- Registers --
   ---------------

   --  Description collection[0]: Trigger 0 for triggering the corresponding TRIGGERED[0] event

   --  Description collection[0]: Trigger 0 for triggering the corresponding
   --  TRIGGERED[0] event
   type TASKS_TRIGGER_Registers is array (0 .. 15) of Interfaces.NRF52.UInt32
     with Volatile;

   --  Description collection[0]: Event number 0 generated by triggering the corresponding TRIGGER[0] task

   --  Description collection[0]: Event number 0 generated by triggering the
   --  corresponding TRIGGER[0] task
   type EVENTS_TRIGGERED_Registers is array (0 .. 15)
     of Interfaces.NRF52.UInt32
     with Volatile;

   --  Enable or disable interrupt for TRIGGERED[0] event
   type INTEN_TRIGGERED0_Field is
     (
      --  Disable
      Disabled,
      --  Enable
      Enabled)
     with Size => 1;
   for INTEN_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  INTEN_TRIGGERED array
   type INTEN_TRIGGERED_Field_Array is array (0 .. 15)
     of INTEN_TRIGGERED0_Field
     with Component_Size => 1, Size => 16;

   --  Type definition for INTEN_TRIGGERED
   type INTEN_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : Interfaces.NRF52.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTEN_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTEN_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Enable or disable interrupt
   type INTEN_Register is record
      --  Enable or disable interrupt for TRIGGERED[0] event
      TRIGGERED      : INTEN_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : Interfaces.NRF52.UInt16 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for INTEN_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   --  Write '1' to Enable interrupt for TRIGGERED[0] event
   type INTENSET_TRIGGERED0_Field is
     (
      --  Read: Disabled
      Disabled,
      --  Read: Enabled
      Enabled)
     with Size => 1;
   for INTENSET_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  Write '1' to Enable interrupt for TRIGGERED[0] event
   type INTENSET_TRIGGERED0_Field_1 is
     (
      --  Reset value for the field
      Intenset_Triggered0_Field_Reset,
      --  Enable
      Set)
     with Size => 1;
   for INTENSET_TRIGGERED0_Field_1 use
     (Intenset_Triggered0_Field_Reset => 0,
      Set => 1);

   --  INTENSET_TRIGGERED array
   type INTENSET_TRIGGERED_Field_Array is array (0 .. 15)
     of INTENSET_TRIGGERED0_Field_1
     with Component_Size => 1, Size => 16;

   --  Type definition for INTENSET_TRIGGERED
   type INTENSET_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : Interfaces.NRF52.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTENSET_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTENSET_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Enable interrupt
   type INTENSET_Register is record
      --  Write '1' to Enable interrupt for TRIGGERED[0] event
      TRIGGERED      : INTENSET_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : Interfaces.NRF52.UInt16 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for INTENSET_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   --  Write '1' to Disable interrupt for TRIGGERED[0] event
   type INTENCLR_TRIGGERED0_Field is
     (
      --  Read: Disabled
      Disabled,
      --  Read: Enabled
      Enabled)
     with Size => 1;
   for INTENCLR_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  Write '1' to Disable interrupt for TRIGGERED[0] event
   type INTENCLR_TRIGGERED0_Field_1 is
     (
      --  Reset value for the field
      Intenclr_Triggered0_Field_Reset,
      --  Disable
      Clear)
     with Size => 1;
   for INTENCLR_TRIGGERED0_Field_1 use
     (Intenclr_Triggered0_Field_Reset => 0,
      Clear => 1);

   --  INTENCLR_TRIGGERED array
   type INTENCLR_TRIGGERED_Field_Array is array (0 .. 15)
     of INTENCLR_TRIGGERED0_Field_1
     with Component_Size => 1, Size => 16;

   --  Type definition for INTENCLR_TRIGGERED
   type INTENCLR_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : Interfaces.NRF52.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTENCLR_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTENCLR_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Disable interrupt
   type INTENCLR_Register is record
      --  Write '1' to Disable interrupt for TRIGGERED[0] event
      TRIGGERED      : INTENCLR_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : Interfaces.NRF52.UInt16 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for INTENCLR_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   -----------------
   -- Peripherals --
   -----------------

   --  Event Generator Unit 0
   type EGU_Peripheral is record
      --  Description collection[0]: Trigger 0 for triggering the corresponding
      --  TRIGGERED[0] event
      TASKS_TRIGGER    : aliased TASKS_TRIGGER_Registers;
      --  Description collection[0]: Event number 0 generated by triggering the
      --  corresponding TRIGGER[0] task
      EVENTS_TRIGGERED : aliased EVENTS_TRIGGERED_Registers;
      --  Enable or disable interrupt
      INTEN            : aliased INTEN_Register;
      --  Enable interrupt
      INTENSET         : aliased INTENSET_Register;
      --  Disable interrupt
      INTENCLR         : aliased INTENCLR_Register;
   end record
     with Volatile;

   for EGU_Peripheral use record
      TASKS_TRIGGER    at 16#0# range 0 .. 511;
      EVENTS_TRIGGERED at 16#100# range 0 .. 511;
      INTEN            at 16#300# range 0 .. 31;
      INTENSET         at 16#304# range 0 .. 31;
      INTENCLR         at 16#308# range 0 .. 31;
   end record;

   --  Event Generator Unit 0
   EGU0_Periph : aliased EGU_Peripheral
     with Import, Address => System'To_Address (16#40014000#);

   --  Event Generator Unit 1
   EGU1_Periph : aliased EGU_Peripheral
     with Import, Address => System'To_Address (16#40015000#);

   --  Event Generator Unit 2
   EGU2_Periph : aliased EGU_Peripheral
     with Import, Address => System'To_Address (16#40016000#);

   --  Event Generator Unit 3
   EGU3_Periph : aliased EGU_Peripheral
     with Import, Address => System'To_Address (16#40017000#);

   --  Event Generator Unit 4
   EGU4_Periph : aliased EGU_Peripheral
     with Import, Address => System'To_Address (16#40018000#);

   --  Event Generator Unit 5
   EGU5_Periph : aliased EGU_Peripheral
     with Import, Address => System'To_Address (16#40019000#);

end Interfaces.NRF52.EGU;
